<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/lib/html5shiv.js"></script>
    <script type="text/javascript" src="/lib/respond.min.js"></script>
    <![endif]-->
    <link href="/static/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="/static/h-ui.admin/css/H-ui.login.css" rel="stylesheet" type="text/css" />
    <link href="/static/h-ui.admin/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/lib/Hui-iconfont/1.0.8/iconfont.css" rel="stylesheet" type="text/css" />
    <!--[if IE 6]>
    <script type="text/javascript" src="http://lib.h-ui.net/DD_belatedPNG_0.0.8a-min.js" ></script>
    <script>DD_belatedPNG.fix('*');</script><![endif]-->
    <title>添加apikey</title>
</head>
<body>
<div class="">
    <div id="loginform" class="">
        <form class="form form-horizontal" action="##" method="post" id="loginform" name="loginform">
            <input id="id" name="id" hidden value="<?=$res["id"]?>">
            <div class="row cl">
                <label class="form-label col-xs-2"></label>
                <div class="formControls col-xs-8">
                    <input id="domain" name="domain" type="text" placeholder="domain" class="input-text size-L" value="<?=$res["Domain"]?>">
                </div>
            </div>

            <div class="row cl">
                <label class="form-label col-xs-2">api</label>
                <div class="formControls col-xs-8">
                    <input id="apikey" name="apikey" type="text" placeholder="apikey" class="input-text size-L" value="<?=$res["apikey"]?>">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">第一代apikey</label>
                <div class="formControls col-xs-8">
                    <input id="apikey1" name="apikey1" type="text" placeholder="第一代apikey" class="input-text size-L" value="<?=$res["apikey1"]?>">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">holderid</label>
                <div class="formControls col-xs-8">
                    <input id="holderid" name="holderid" type="text" value="<?=$res["holderid"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">clonedomain</label>
                <div class="formControls col-xs-8">
                    <input id="clonedomain" name="clonedomain" type="text" value="<?=$res["clonedomain"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">email</label>
                <div class="formControls col-xs-8">
                    <input id="email" name="email" type="text" value="<?=$res["email"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">扩展名id（nl为4；be为10）</label>
                <div class="formControls col-xs-8">
                    <input id="extent_id" name="extent_id" type="text" value="<?=$res["extent_id"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">密码</label>
                <div class="formControls col-xs-8">
                    <input id="apipassword" name="apipassword" type="text" placeholder="password" class="input-text size-L" value="<?=$res["password"]?>">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">开始时间</label>
                <div class="formControls col-xs-8">
                    <input id="start_time" name="start_time" type="text" value="<?=date("Y-m-d H:i:s",$res["start_time"])?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">结束时间</label>
                <div class="formControls col-xs-8">
                    <input id="end_time" name="end_time" type="text" value="<?=date("Y-m-d H:i:s",$res["end_time"])?>"  class="input-text size-L">
                </div>
            </div>

<!--                <label class="form-label col-xs-2"></label>-->
<!--                <div class="formControls col-xs-8">-->
<!--                    <input id="registrant_organization" name="registrant_organization" type="text" placeholder="公司" class="input-text size-L">-->
<!--                </div>-->
<!--            </div>-->

            <div class="row cl">
                <div class="formControls col-xs-8 col-xs-offset-3">
                    <input id="login" name="login" type="button" class="btn btn-success radius size-L" value="&nbsp;提&nbsp;&nbsp;&nbsp;&nbsp;交&nbsp;">
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript">
    $(function(){
        $('#login').click(function(){
            $.ajax({
                url:'edit',
                type:'POST',
                // data:$('#loginform').serialize(),
                data:{
                    id:$("#id").val(),
                    con_email:$("#con_email").val(),
                    Domain:$("#domain").val(),
                    ApiKey:$("#apikey").val(),
                    ApiKey1:$("#apikey1").val(),
                    Password:$("#apipassword").val(),
                    holderid:$("#holderid").val(),
                    start_time:$("#start_time").val(),
                    end_time:$("#end_time").val(),
                    extent_id:$("#extent_id").val(),
                    clonedomain:$("#clonedomain").val(),
                    email:$("#email").val(),
                    // registrant_firstname:$("#registrant_firstname").val(),
                    // registrant_lastname:$("#registrant_lastname").val(),
                    // // registrant_organization:$("#registrant_organization").val(),
                    // registrant_street:$("#registrant_street").val(),
                    // registrant_city:$("#registrant_city").val(),
                    // registrant_countrycode:$("#registrant_countrycode").val(),
                    // registrant_postalcode:$("#registrant_postalcode").val(),
                    // registrant_email:$("#registrant_email").val(),
                    // registrant_phonenumber:$("#registrant_phonenumber").val(),
                },
                dataType:'json',
                success:function(msg){
                    if(msg.errno==1){
                        alert(msg.errmsg);
                        window.parent.location.reload(); //刷新父页面
                        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
                        parent.layer.close(index);  // 关闭layer
                    }else{
                        alert(msg.errmsg);
                    }
                }
            })
        })
    })
</script>

</body>
</html>