<?php include (APPLICATION_PATH."/application/views/header.phtml");?>
<?php include (APPLICATION_PATH."/application/views/menu.phtml");?>
<div class="dislpayArrow hidden-xs">
    <a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a>
</div>
<!--/_menu 作为公共模版分离出去-->
<form action="" method="post" class="form form-horizontal" id="form-goods-add" enctype="multipart/form-data">
<section class="Hui-article-box">

    <div class="Hui-article">
        <article class="cl pd-20">
            <div class="cl pd-5 bg-1 bk-gray mt-20">
				<span class="l">

                 <input class="btn btn-danger radius" type="button" name="submit" id="submit"  value="批量删除" onclick="alldel();">
                            <select class="btn btn-primary radius"  name="template"  id="template">
                                 <?php foreach ($tempmodels as $template):?>
                                <option value="<?=$template["id"]?>"><?=$template["name"]?></option>
                                 <?php endforeach; ?>
                            </select>
                    <a href="javascript:;" onclick="member_add('添加','addv','800','700')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加</a></span>
            </div>
            <div class="mt-20">
                <table class="table table-border table-bordered table-bg table-hover table-sort">
                    <thead>
                    <tr class="text-c">
                        <th width="25"><input type="checkbox" name="" value=""></th>
                        <th width="80">ID</th>
                        <th>名称</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($res as $values):?>
                    <tr class="text-c">
                        <td><input type="checkbox" value="<?=$values["id"]?>" name="delete_id[]" id="delete_id[]"></td>
                        <td><?=$values["id"]?></td>
                        <td><?=$values["Domain"]?></td>
                        <td><?=date("Y-m-d H:i:s",$values["start_time"])?></td>
                        <td><?=date("Y-m-d H:i:s",$values["end_time"])?></td>
                        <td class="f-14 td-manage">
                            <a title="编辑" href="javascript:;" onclick="member_edit('编辑','editv','<?=$values["id"]?>','','510')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6df;</i></a>
                            <a title="删除" href="javascript:;" onclick="member_del(this,'<?=$values["id"]?>')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </article>
    </div>
</section>
</form>
<!--_footer 作为公共模版分离出去-->

<?php include (APPLICATION_PATH."/application/views/js.phtml");?>
<!--/_footer /作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="/lib/My97DatePicker/4.8/WdatePicker.js"></script>
<script type="text/javascript" src="/lib/datatables/1.10.0/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/lib/laypage/1.2/laypage.js"></script>
<script type="text/javascript">
    $('.table-sort').dataTable({
        "aaSorting": [[ 1, "desc" ]],//默认第几个排序
        "bStateSave": true,//状态保存
        "aoColumnDefs": [
            //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
            // {"orderable":false,"aTargets":[0,8]}// 不参与排序的列
        ]
    });

    function member_add(title,url,w,h){
        id=$('#template option:selected') .val();
        url=url+"?id="+id+"&model=1";
        layer_show(title,url,w,h);
    }
    /*资讯-删除*/
    function article_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.ajax({
                type: 'POST',
                url: '',
                dataType: 'json',
                success: function(data){
                    $(obj).parents("tr").remove();
                    layer.msg('已删除!',{icon:1,time:1000});
                },
                error:function(data) {
                    console.log(data.msg);
                },
            });
        });
    }
    function member_edit(title,url,id,w,h){
        url=url+"?id="+id+"&model=1";
        layer_show(title,url,w,h);
    }
    function member_del(obj,id){
        layer.confirm('确认要删除吗？',function(index){
            $.get("delete?id="+id);
            $(obj).parents("tr").remove();
            layer.msg('已删除!',{icon:1,time:1000});
        });
    }

    function alldel(){
        var form = new FormData(document.getElementById("form-goods-add"));
            $.ajax({
                url:'/domains/alldelete',
                type:'POST',
                // data: $('#loginform').serialize(),
                processData:false,
                contentType:false,
                data:form,
                dataType:'json',
                success:function(msg){
                    if(msg.errno==1){
                        alert(msg.errmsg);
                        window.parent.location.reload();
                    }else{
                        alert(msg.errmsg);
                    }
                }
            })
    }
</script>
<!--/请在上方写此页面业务相关的脚本-->
</body>
</html>