<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="/lib/html5shiv.js"></script>
<script type="text/javascript" src="/lib/respond.min.js"></script>
<![endif]-->
<link href="/static/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />
<link href="/static/h-ui.admin/css/H-ui.login.css" rel="stylesheet" type="text/css" />
<link href="/static/h-ui.admin/css/style.css" rel="stylesheet" type="text/css" />
<link href="/lib/Hui-iconfont/1.0.8/iconfont.css" rel="stylesheet" type="text/css" />
<!--[if IE 6]>
<script type="text/javascript" src="http://lib.h-ui.net/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script><![endif]-->
<title>添加apikey</title>
</head>
<body>
<input type="hidden" id="TenantId" name="TenantId" value="" />

<div class="loginWraper">
	<div id="loginform" class="loginBox">
		<form class="form form-horizontal" action="##" method="post" id="loginform" name="loginform">
            <div class="row cl">
                <label class="form-label col-xs-2">paikey</label>
                <div class="formControls col-xs-8">
                    <input id="keys" name="keys" type="text" placeholder="apikey" class="input-text size-L" value="<?=$res["nlkeys"]?>">
                </div>
            </div>
			<div class="row cl">
				<label class="form-label col-xs-2">秘钥</label>
				<div class="formControls col-xs-8">
					<input id="miyao" name="miyao" type="text" placeholder="秘钥" class="input-text size-L" value="<?=$res["password"]?>">
				</div>
			</div>
            <div class="row cl">
                <label class="form-label col-xs-2">开始时间</label>
                <div class="formControls col-xs-8">
                    <input id="start_time" name="start_time" type="text" value="<?=date("Y-m-d H:i:s",$res["start_time"])?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">结束时间</label>
                <div class="formControls col-xs-8">
                    <input id="end_time" name="end_time" type="text" value="<?=date("Y-m-d H:i:s",$res["end_time"])?>"  class="input-text size-L">
                </div>
            </div>
            <input hidden id="id" name="id" value="<?=$res["id"]?>">
			<div class="row cl">
				<div class="formControls col-xs-8 col-xs-offset-3">
                    <input id="login" name="login" type="button" class="btn btn-success radius size-L" value="&nbsp;提&nbsp;&nbsp;&nbsp;&nbsp;交&nbsp;">
				</div>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript" src="/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript">
    $(function(){
        $('#login').click(function(){
            $.ajax({
                url:'/nlapikey/apikeyEdit/',
                type:'POST',
                // data: $('#loginform').serialize(),
                data:{
					keys:$("#keys").val(),
                    password:$("#miyao").val(),
                    id:$("#id").val(),
                    start_time:$("#start_time").val(),
                    end_time:$("#end_time").val(),
                },
                dataType:'json',
                success:function(msg){
                    if(msg.errno==1){
                        alert(msg.errmsg);
                        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
                        parent.layer.close(index);  // 关闭layer
                    }else{
                        alert(msg.errmsg);
                    }
                }
            })
        })
    })
</script>

</body>
</html>