<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/lib/html5shiv.js"></script>
    <script type="text/javascript" src="/lib/respond.min.js"></script>
    <![endif]-->
    <link href="/static/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="/static/h-ui.admin/css/H-ui.login.css" rel="stylesheet" type="text/css" />
    <link href="/static/h-ui.admin/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/lib/Hui-iconfont/1.0.8/iconfont.css" rel="stylesheet" type="text/css" />
    <!--[if IE 6]>
    <script type="text/javascript" src="http://lib.h-ui.net/DD_belatedPNG_0.0.8a-min.js" ></script>
    <script>DD_belatedPNG.fix('*');</script><![endif]-->
    <title>添加apikey</title>
</head>
<body>
<div class="">
    <div id="loginform" class="">
        <form class="form form-horizontal" action="##" method="post" id="loginform" name="loginform">
            <div class="row cl">
                <label class="form-label col-xs-2">名称</label>
                <div class="formControls col-xs-8">
                    <input id="name" name="name" type="text" placeholder="name" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">extent_id（nl为4；be为10）</label>
                <div class="formControls col-xs-8">
                    <input id="extent_id" name="extent_id" type="text" placeholder="extent_id" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">apikey</label>
                <div class="formControls col-xs-8">
                    <input id="apikey" name="apikey" type="text" placeholder="apikey" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">第一代apikey</label>
                <div class="formControls col-xs-8">
                    <input id="apikey1" name="apikey1" type="text" placeholder="第一代apikey" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">versio 账号:密码</label>
                <div class="formControls col-xs-8">
                    <input id="versio_userpwd" name="versio_userpwd" type="text" placeholder="versio_userpwd" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">versio 联系人id</label>
                <div class="formControls col-xs-8">
                    <input id="versio_contentid" name="versio_contentid" type="text" placeholder="versio_contentid" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">密码</label>
                <div class="formControls col-xs-8">
                    <input id="apipassword" name="apipassword" type="text" placeholder="password" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">holderid</label>
                <div class="formControls col-xs-8">
                    <input id="holderid" name="holderid" type="text" value="<?=$res["holderid"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">clonedomain(复制此域名联系方式)</label>
                <div class="formControls col-xs-8">
                    <input id="clonedomain" name="clonedomain" type="text" value="<?=$res["clonedomain"]?>" class="input-text size-L">
                </div>
            </div>
            <div class="row cl">
                <label class="form-label col-xs-2">email</label>
                <div class="formControls col-xs-8">
                    <input id="email" name="email" type="text" value="<?=$res["email"]?>" class="input-text size-L">
                </div>
            </div>
<!--            <div class="row cl">-->
<!--                <label class="form-label col-xs-2"></label>-->
<!--                <div class="formControls col-xs-8">-->
<!--                    <input id="registrant_organization" name="registrant_organization" type="text" placeholder="公司" class="input-text size-L">-->
<!--                </div>-->
<!--            </div>-->
            <div class="row cl">
                <div class="formControls col-xs-8 col-xs-offset-3">
                    <input id="login" name="login" type="button" class="btn btn-success radius size-L" value="&nbsp;提&nbsp;&nbsp;&nbsp;&nbsp;交&nbsp;">
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="/lib/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/h-ui/js/H-ui.js"></script>
<script type="text/javascript">
    $(function(){
        $('#login').click(function(){
            $.ajax({
                url:'add',
                type:'POST',
                // data:$('#loginform').serialize(),
                data:{
                    name:$("#name").val(),
                    apikey:$("#apikey").val(),
                    apikey1:$("#apikey1").val(),
                    password:$("#apipassword").val(),
                    holderid:$("#holderid").val(),
                    extent_id:$("#extent_id").val(),
                    clonedomain:$("#clonedomain").val(),
                    email:$("#email").val(),
                    versio_contentid:$("#versio_contentid").val(),
                    versio_userpwd:$("#versio_userpwd").val(),
                },
                dataType:'json',
                success:function(msg){
                    if(msg.errno==1){
                        alert(msg.errmsg);
                        window.parent.location.reload(); //刷新父页面
                        var index = parent.layer.getFrameIndex(window.name); //获取窗口索引
                        parent.layer.close(index);  // 关闭layer
                    }else{
                        alert(msg.errmsg);
                    }
                }
            })
        })
    })
</script>

</body>
</html>